name: jikan_api
version: 1.6.1
description: Dart wrapper for the Jikan API, an unofficial MyAnimeList API.
homepage: https://github.com/javoeria/jikan-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4
  built_value: ^8.1.4
  built_collection: ^5.1.1

dev_dependencies:
  build_runner: ^2.1.7
  built_value_generator: ^8.1.4
  lints: ^1.0.1
  test: ^1.20.1
