name: jikan_api
version: 2.0.0
description: Dart wrapper for the Jikan API, an unofficial MyAnimeList API.
homepage: https://github.com/javoeria/jikan-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.5
  built_value: ^8.4.1
  built_collection: ^5.1.1

dev_dependencies:
  build_runner: ^2.2.0
  built_value_generator: ^8.4.1
  lints: ^2.0.0
  test: ^1.21.4
