name: jikan_api
version: 2.1.0
description: Dart wrapper for the Jikan API, an unofficial MyAnimeList API.
homepage: https://github.com/javoeria/jikan-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.5
  built_value: ^8.4.4
  built_collection: ^5.1.1

dev_dependencies:
  build_runner: ^2.3.3
  built_value_generator: ^8.4.4
  lints: ^2.0.1
  test: ^1.23.1
